# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97df54ef921339862d78821f36cc5ab79bbfa129f6e759db197dfd4333d736db1ca6c74353f2481a4f25f307936a8dea6442f24077cead9551a1e636b90f68fc

test:
  secret_key_base: 0924c19c263147afbe6296dea49a19e753359185ee2dab99f25cc5b4eee0db68393ecb865a54aa4a51a510f4348a117b533c0281667dc4c420dad80d3fb388cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
